# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Button"
  description: ""
  icon: "crop_7_5"
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  label: "Button"
  button_type: 
  link_url: 
  open_in_new_tab: false 
  width: 
      - "Small"


# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  label: "Button"
  button_type: "Primary"
  link_url: "/"
  open_in_new_tab: false 
  width: 
    - "Small"

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  width:
    type: select
    options:
      values:
        - "Small"
        - "Large"
  button_type:
    type: select
    options:
      values:
      - "Primary"
      - "Secondary"
    